module ChambaSearchMx
  ##
  # available locations
  LOCATIONS = {
    ags:      'empleos-en-aguascalientes',
    bcn:      'empleos-en-baja-california',
    bcs:      'empleos-en-baja-california-sur',
    cam:      'empleos-en-campeche',
    chi:      'empleos-en-chihuahua',
    chp:      'empleos-en-chiapas',
    coa:      'empleos-en-coahuila',
    col:      'empleos-en-colima',
    default:  'empleos-en-mexico-y-el-mundo',
    df:       'empleos-en-df-y-zona-metro',
    dgo:      'empleos-en-durango',
    gro:      'empleos-en-guerrero',
    gto:      'empleos-en-guanajuato',
    hgo:      'empleos-en-hidalgo',
    jal:      'empleos-en-jalisco',
    mch:      'empleos-en-michoacan',
    mex:      'empleos-en-edo-mexico',
    mor:      'empleos-en-morelos',
    mx:       'empleos-en-empleos-en-mexico',
    nay:      'empleos-en-nayarit',
    nl:       'empleos-en-nuevo león',
    oax:      'empleos-en-oaxaca',
    pue:      'empleos-en-puebla',
    qr:       'empleos-en-quintana roo',
    qro:      'empleos-en-queretaro',
    sina:     'empleos-en-sinaloa',
    slp:      'empleos-en-san luis potose',
    sono:     'empleos-en-sonora',
    tab:      'empleos-en-tabasco',
    tam:      'empleos-en-tamaulipas',
    tlx:      'empleos-en-tlaxcala',
    us:       'empleos-en-estados unidos',
    ver:      'empleos-en-veracruz',
    world:    'empleos-en-resto del mundo',
    yuc:      'empleos-en-yucatán',
    zac:      'empleos-en-zacatecas'
  }.freeze
end
